Fixed set mtu for deleted subintf due to late notification
EdenGri/sonic-swss pull request #4
Opened 2022-12-07 16:42 UTC by EdenGri

**What I did**

Ignores errors on the set MTU command for subinterface when the subinterface state is not OK.

**Why I did it**

A race condition between the portmgrd and the intfmgrd sometimes causes running a set MTU command on a deleted subinterface.
The logs and the error:
```
INFO swss#supervisord: intfmgrd Cannot find device "Ethernet32.58"
ERR swss#intfmgrd: :- main: Runtime error: /sbin/ip link set "Ethernet32.58" mtu "9100" :
INFO swss#supervisord 2022-11-08 05:53:33,057 INFO exited: intfmgrd (exit status 255; not expected)
```

**How I verified it**

Run the test_loopback_action_reload test and saw no errors in the logs.

**Details if related**

2022-12-07 23:25 UTC, dprital commented on cfgmgr/intfmgr.cpp
> +        // Can happen when a DEL notification is sent by portmgrd immediately followed by a new SET notif
The comment is not clear. Please describe the scenario in which we will get the error by "mistake"

2022-12-07 23:27 UTC, dprital requested changes

2022-12-07 23:27 UTC, dprital commented on cfgmgr/intfmgr.cpp
> +        // Can happen when a DEL notification is sent by portmgrd immediately followed by a new SET notif
The comment is not clear. Please describe the scenario in which we will get the error by "mistake"

2022-12-07 23:27 UTC, dprital commented on cfgmgr/intfmgr.cpp
> +        SWSS_LOG_WARN("Setting mtu to alias:%s netdev failed with cmd:%s, rc:%d, error:%s", alias.c_str(), cmd_str.c_str(), ret, res.c_str());
Remove the word :"alias"

2022-12-13 07:40 UTC, EdenGri commented on cfgmgr/intfmgr.cpp
> +        // Can happen when a DEL notification is sent by portmgrd immediately followed by a new SET notif
Done

2022-12-13 07:40 UTC, EdenGri commented on cfgmgr/intfmgr.cpp
> +        SWSS_LOG_WARN("Setting mtu to alias:%s netdev failed with cmd:%s, rc:%d, error:%s", alias.c_str(), cmd_str.c_str(), ret, res.c_str());
Done

2022-12-13 17:32 UTC, dprital approved these changes

2022-12-13 19:59 UTC, closed without merging